export const types = {
    // Sync
    TASK_MANAGER_FILL_TASKS: 'TASK_MANAGER_FILL_TASKS',
    TASK_MANAGER_START_FETCHING_TASKS: 'TASK_MANAGER_START_FETCHING_TASKS',
    TASK_MANAGER_FETCH_WITH_ERROR: 'TASK_MANAGER_FETCH_WITH_ERROR',
    TASK_MANAGER_FINISH_FETCHING_TASKS: 'TASK_MANAGER_FINISH_FETCHING_TASKS',

    TASK_MANAGER_START_CREATING_TASK: 'TASK_MANAGER_START_CREATING_TASK',
    TASK_MANAGER_CREATE_WITH_ERROR: 'TASK_MANAGER_CREATE_WITH_ERROR',
    TASK_MANAGER_FINISH_CREATING_TASK: 'TASK_MANAGER_FINISH_CREATING_TASK',

    TASK_MANAGER_START_UPDATING_TASK: 'TASK_MANAGER_START_UPDATING_TASK',
    TASK_MANAGER_UPDATE_WITH_ERROR: 'TASK_MANAGER_UPDATE_WITH_ERROR',
    TASK_MANAGER_FINISH_UPDATING_TASK: 'TASK_MANAGER_FINISH_UPDATING_TASK',

    TASK_MANAGER_START_DELETING_TASK: 'TASK_MANAGER_START_DELETING_TASK',
    TASK_MANAGER_DELETE_WITH_ERROR: 'TASK_MANAGER_DELETE_WITH_ERROR',
    TASK_MANAGER_FINISH_DELETING_TASK: 'TASK_MANAGER_FINISH_DELETING_TASK',

    //Async
    TASK_MANAGER_FETCH_TASKS_ASYNC: 'TASK_MANAGER_FETCH_TASKS_ASYNC',
    TASK_MANAGER_CREATE_TASK_ASYNC: 'TASK_MANAGER_CREATE_TASK_ASYNC',
    TASK_MANAGER_UPDATE_TASK_ASYNC: 'TASK_MANAGER_UPDATE_TASK_ASYNC',
    TASK_MANAGER_DELETE_TASK_ASYNC: 'TASK_MANAGER_DELETE_TASK_ASYNC'

}